server:
  port: 9999
spring:
  application:
    name: webflux
  datasource:
    url: jdbc:postgresql://localhost:5432/webflux
    username: webflux
    password: webflux
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
